version: '3'

services:
  web:
    build: .
    ports:
      - "6666:5000"
    volumes:
      - .:/app
    environment:
      - FLASK_APP=app/main.py
      - FLASK_ENV=development
    command: python main.py
    restart: always